#
# Makefile
# $Log$
# Revision 1.1  2006/12/06 19:46:26  andreas
# commited initial draft of the redd_kickstart manual
#
# Revision 1.1  2005/01/18 19:51:19  georgs
# added kfi paper to doc/investigation/kfi-paper/
# sources are in doc/investigation/kfi/...
# furthermore i updated the week report
#
#


# Makefile for LaTeX documents

# TEXFILES = $(wildcard *.tex)

#TEXFILES contains usually only the header file
#The pdf file will be called header_docu.pdf, so you better give
#a suitable name for your header file
TEXFILES = XMeRTL_Manual.tex
DEPS = XMeRTL_Manual.tex content.tex intro.tex install.tex interdomain.tex xmdev.tex xmtrace.tex examples.tex bibliography.tex hypercalls.tex
include latex/Makefile

